name: CI
on: [push, pull_request]

env:
  ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: http://arduino.esp8266.com/stable/package_esp8266com_index.json

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP8266
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266
      - name: Install AirGradient Library
        run: |
          arduino-cli lib install "AirGradient Air Quality Sensor"
      - name: Install SSD1306 Display Library
        run: |
          arduino-cli lib install "ESP8266 and ESP32 OLED driver for SSD1306 displays"
      - name: Install Home Assistant Integration
        run: |
          arduino-cli lib install "home-assistant-integration"@1.3.0
      - name: Create config header
        run: |
          cp ./DeviceConfig.example.hpp ./DeviceConfig.hpp
      - name: Compile Sketch
        run: arduino-cli compile --fqbn esp8266:esp8266:d1_mini ./AirGradientHomeAssistant.ino

